FROM python:3.13.2-bookworm AS builder

SHELL ["/bin/bash", "-c"] 

# Colorized Terminal
ENV TERM=xterm-256color
RUN echo "PS1='\e[92m\u\e[0m@\e[94m\h\e[0m:\e[35m\w\e[0m# '" >> ~/.bashrc
RUN echo "export TERM=xterm-256color" >> ~/.bashrc
RUN echo alias ls="'"'ls --color=auto'"'" >> ~/.bashrc

ENV BUILD_ENVIRONMENT=ci
ENV PYTHONPATH=/radarETL

# Update apt
RUN apt-get update
# Install some fundamentals for monitoring and editing
RUN apt install -y htop btop bmon cron nano vim wget netcat-openbsd

RUN mkdir /radarETL

# Upgrade pip to latest version before package installs
RUN pip install --upgrade pip

RUN pip install requests boto3 pylint psycopg2-binary

CMD tail -f /dev/null