FROM python:3.13.2-bookworm AS builder

SHELL ["/bin/bash", "-c"] 

# Colorized Terminal
ENV TERM=xterm-256color
RUN echo "PS1='\e[92m\u\e[0m@\e[94m\h\e[0m:\e[35m\w\e[0m# '" >> ~/.bashrc
RUN echo "export TERM=xterm-256color" >> ~/.bashrc
RUN echo alias ls="'"'ls --color=auto'"'" >> ~/.bashrc

ENV BUILD_ENVIRONMENT=ci
ENV PYTHONPATH=/radarETL

# Update apt
RUN apt-get update
# All these dependencies may not be needed. 
# Install some fundamentals for monitoring and editing
RUN apt install -y htop btop bmon cron nano vim wget netcat-openbsd logrotate
RUN apt install -y make cmake gcc g++ gfortran openmpi-bin openmpi-common libopenmpi-dev \
libcairo2-dev libjpeg-dev libpng-dev libpq-dev libxml2-dev libzstd-dev \
libhdf5-dev zlib1g-dev
# Install Other Apt Dependencies
RUN apt-get install -y libeccodes-dev libeccodes-tools libffi-dev libgeotiff-dev libgeos-dev libheif-dev libheif-examples
# Make a few directories
RUN mkdir /radarETL
RUN mkdir /dependencyBuilds

# Upgrade pip to latest version before package installs
RUN pip install --upgrade pip

RUN pip install requests boto3 pylint psycopg2-binary pytest
RUN pip install metpy==1.6.3

WORKDIR /radarETL

CMD tail -f /dev/null